resolver: 'lts-19.17'
system-ghc: true
skip-ghc-check: true
packages:
- '.'
- '../hakyll/'
nix:
  packages:
  - graphviz
  - imagemagick
  - texlive.combined.scheme-full  # Just for `standalone.cls`, urgh!
  - zlib
  - openssh
  - rsync
