resolver: 'lts-20.10'
packages:
- '.'
extra-deps:
- 'hakyll-4.15.1.1'
nix:
  packages:
  - graphviz
  - ghostscript_headless  # latex dependency for illustrations in posts/2013-11-21-random-element-frequency-list.html
  - imagemagick
  - texlive.combined.scheme-full  # Just for `standalone.cls`, urgh!
  - zlib
  - openssh
  - rsync
  - pkg-config
