resolver: 'lts-20.10'
packages:
- '.'
extra-deps:
- 'hakyll-4.15.1.1'
nix:
  packages:
  - graphviz
  - imagemagick
  - texlive.combined.scheme-full  # Just for `standalone.cls`, urgh!
  - zlib
  - openssh
  - rsync
  - pkgconfig
